title: Sammy Geller
author: sgeller98
email: geller.sammy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A CS student trying to figure out the best way to make it and still enjoy myself

# social links
github_username:  sgeller98

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
